### ISSUE TITLE
Options do not work

### ISSUE THREAD

**Issue by saswatds** [ziscloud/angular-slimscroll#22]
The options which i put doesnt seem to take any effect on the slimscroll. The touch responsize is very bad too

**Comment by ioncube** [comment]
Noticed this too after an update. Removing `$($elem).slimScroll({ destroy: true });` seems to resolve, however this has been in the code since the 2nd commit and is likely necessary. Still exploring this.

**Comment by ioncube** [comment]
The underlying cause may be to do with slimscroll itself or elsewhere, but this is fixed by putting back a call to `refresh()` that used to be at the top of `init()` (now called `registerWatch()`). You may also want to add `noWatch` to your options as slimscroll might be being destroyed and reinstated several times.

**Comment by TomOffringa** [comment]
Is there a proper solution for this already? Walking into this issue as well.

**Comment by W-prog** [comment]
Hi, 
Have you an issue for this .
I call
```
[code]
<div class="scroll-body" slimscroll="{noWatch:true,railColor:'#FF69B4'}" style="height: 150px;">
[/code]
```

And nothing effect color to the scroolbar.
Maybe I don't understood ?
